CREATE OR REPLACE VIEW [PlanviewMigration_Transform_Output].[vw_Initiatives_Consolidated] AS

SELECT

    /* ==========================================
       SECTION 1: [PlanviewMigration_Output].[Initiatives_v12] - BASE COLUMNS
       Alias: a
       Excluded: Run_ID, Save_Timestamp, Does this require Limited Visibility?, Stage
       ========================================== */

    COALESCE(a.[Strategy Seq ID],                   b.[Strategy Seq ID],                            c.[Strategy Seq ID])                                                AS [Strategy Seq ID],
    COALESCE(a.[Name Long Form],                    b.[Name (Long Form)],                           c.[Name (Long Form)])                                               AS [Name Long Form],
    COALESCE(a.[Lifecycle Model],                   b.[Lifecycle Model],                            c.[Lifecycle Model])                                                AS [Lifecycle Model],
    COALESCE(a.[Name],                              b.[Name],                                       c.[Name])                                                           AS [Name],
    a.[Description]                                                                                                                                                     AS [Description],
    COALESCE(a.[Expected Business Outcome],         b.[Expected Business Outcome],                  c.[Expected Business Outcome])                                      AS [Expected Business Outcome],
    COALESCE(a.[Is this request vital to business continuity],
             b.[Is this request vital to business continuity?],
             c.[Is this request vital to business continuity?])                                                                                                         AS [Is this request vital to business continuity],
    COALESCE(a.[Home Portfolio],                    b.[Home Portfolio],                             c.[Home Portfolio])                                                 AS [Home Portfolio],
    COALESCE(a.[Impacts Value Prop or Risk to Customer?],
             b.[Impacts Value Prop or Risk to Customer Service?],
             c.[Impacts Value Prop or Risk to Customer Service?])                                                                                                       AS [Impacts Value Prop or Risk to Customer?],
    COALESCE(a.[Request Type],                      b.[Request Type],                               c.[Request Type])                                                   AS [Request Type],
    COALESCE(a.[Demand Type],                       b.[Demand Type],                                c.[Demand Type])                                                    AS [Demand Type],
    COALESCE(a.[Demand SubType],                    b.[Demand SubType],                             c.[Demand SubType])                                                 AS [Risk Subtype (Does this request address a risk or requirement to one of the following?)],
    COALESCE(a.[Exclude from Migratlon],            b.[Exclude from Migratlon],                     c.[Exclude from Migratlon])                                         AS [Exclude from Migratlon],
    COALESCE(a.[Primary Type of Value],             b.[Primary Type of Value],                      c.[Primary Type of Value])                                          AS [Primary Type of Value],
    COALESCE(a.[Primary Type of Value Impact],      b.[Primary Type of Value Impact],               c.[Primary Type of Value Impact])                                   AS [Primary Type of Value Impact],
    COALESCE(a.[Enterprise Strategic Initiative ESI],
             b.[Enterprise Strategic Initiative (ESI)],
             c.[Enterprise Strategic Initiative (ESI)])                                                                                                                 AS [Enterprise Strategic Initiative ESI],
    COALESCE(a.[Estimated Annualized Value Range],  b.[Estimated Annualized Value Range],           c.[Estimated Annualized Value Range])                               AS [Estimated Annualized Value Range],
    COALESCE(a.[DRIVE Meta Domain Demand Generator],
             b.[DRIVE Meta Domain (Demand Generator)],
             c.[DRIVE Meta Domain (Demand Generator)])                                                                                                                  AS [DRIVE Meta Domain Demand Generator],
    COALESCE(a.[Meta Domain],                       b.[Meta Domain],                                c.[Meta Domain])                                                    AS [Meta Domain],
    COALESCE(a.[Domain],                            b.[Domain],                                     c.[Domain])                                                         AS [Domain],
    a.[What Business Unit does this request support?]                                                                                                                   AS [What Business Unit does this request support?],
    COALESCE(a.[DRIVE Pod Name],                    b.[DRIVE Pod Name],                             c.[DRIVE Pod Name])                                                 AS [DRIVE Pod Name],
    COALESCE(a.[NRB Exit Rate 2028 Latest Estimate.],
             b.[NRB (Exit Rate) 2028 (Latest Estimate).],
             c.[NRB (Exit Rate) 2028 (Latest Estimate).])                                                                                                               AS [NRB Exit Rate 2028 Latest Estimate.],
    COALESCE(a.[Pod],                               b.[Pod],                                        c.[Pod])                                                            AS [Pod],
    COALESCE(a.[DRIVE Pod Lead],                    b.[DRIVE Pod Lead],                             c.[DRIVE Pod Lead])                                                 AS [DRIVE Pod Lead],
    COALESCE(a.[Domain Sponsor],                    b.[Domain Sponsor],                             c.[Domain Sponsor])                                                 AS [Domain Sponsor],
    COALESCE(a.[Sponsor Name],                      b.[Sponsor Name],                               c.[Sponsor Name])                                                   AS [Sponsor Name],
    COALESCE(a.[Initiative Owner],                  b.[Initiative Owner],                           c.[Initiative Owner])                                               AS [Initiative Owner],
    COALESCE(a.[Business Process and_or Operational Impact],
             b.[Business Process and/or Operational Impact],
             c.[Business Process and/or Operational Impact])                                                                                                            AS [Business Process and/or Operational Impact],
    COALESCE(a.[Business Ability To Statements],    b.[Ability To Statements],                      c.[Ability To Statements])                                          AS [Business Ability To Statements],
    COALESCE(a.[Status],                            b.[Lifecycle Status],                           c.[Lifecycle Status])                                               AS [Status],
    COALESCE(a.[Health Status],                     b.[Health Status],                              c.[Health Status])                                                  AS [Health Status],
    COALESCE(a.[Status Rationale],                  b.[Status Rationale],                           c.[Status Rationale])                                               AS [Status Rationale],
    COALESCE(a.[Baseline Fiscal Year of Work Bundle],
             b.[Baseline Fiscal Year of Initiative],
             c.[Baseline Fiscal Year of Initiative])                                                                                                                    AS [Baseline Fiscal Year of Work Bundle],
    COALESCE(a.[Baseline Value],                    b.[Baseline Value],                             c.[Baseline Value])                                                 AS [Baseline Value],
    COALESCE(a.[Measure & Unit],                    b.[Measure & Unit],                             c.[Measure & Unit])                                                 AS [Measure & Unit],
    COALESCE(a.[T-Shirt Size],                      b.[T-Shirt Size],                               c.[T-Shirt Size])                                                   AS [T-Shirt Size],
    COALESCE(a.[L1 Net Recurring Benefits $_ annualized-P&L_Hard],
             b.[L1 Net Recurring Benefits ($, annualized)-P&L/Hard],
             c.[L1 Net Recurring Benefits ($, annualized)-P&L/Hard])                                                                                                   AS [L1 Net Recurring Benefits $_ annualized-P&L_Hard],
    COALESCE(a.[Net Recurring Benefits -Soft],
             b.[L1 Net Recurring Benefits ($, annualized)-Soft],
             c.[L1 Net Recurring Benefits ($, annualized)-Soft])                                                                                                        AS [Net Recurring Benefits -Soft],
    COALESCE(a.[Key Assumptions Made in Quantifying Impact],
             b.[Key Assumptions Made in Quantifying Impact],
             c.[Key Assumptions Made in Quantifying Impact])                                                                                                            AS [Key Assumptions Made in Quantifying Impact],
    COALESCE(a.[External Spend Category],           b.[External Spend Category],                    c.[External Spend Category])                                        AS [External Spend Category],
    COALESCE(a.[What is the Money Step and how will it be measured],
             b.[What is the Money Step and how will it be measured],
             c.[What is the Money Step and how will it be measured])                                                                                                    AS [What is the Money Step and how will it be measured],
    COALESCE(a.[Special Projects],                  b.[Special Projects],                           c.[Special Projects])                                               AS [Special Projects],
    COALESCE(a.[Impacts Commercial Portfolio?],     b.[Impacts Commercial Portfolio?],              c.[Impacts Commercial Portfolio?])                                  AS [Impacts Commercial Portfolio?],
    COALESCE(a.[zz?Impacts Data & AI Portfolio?],   b.[Impacts Data & AI Portfolio?],               c.[Impacts Data & AI Portfolio?])                                   AS [zz?Impacts Data & AI Portfolio?],
    COALESCE(a.[Impacts Enterprise Services Portfolio?],
             b.[Impacts Enterprise Services Portfolio?],
             c.[Impacts Enterprise Services Portfolio?])                                                                                                                AS [Impacts Enterprise Services Portfolio?],
    COALESCE(a.[Impacts Platform Portfolio?],       b.[Impacts Platform Portfolio?],                c.[Impacts Platform Portfolio?])                                    AS [Impacts Platform Portfolio?],
    COALESCE(a.[Impacts Supply Chain Operations Portfolio?],
             b.[Impacts Supply Chain Operations Portfolio?],
             c.[Impacts Supply Chain Operations Portfolio?])                                                                                                            AS [Impacts Supply Chain Operations Portfolio?],
    COALESCE(a.[Change - Number of external stakeholders],
             b.[Change - Number of external stakeholders],
             c.[Change - Number of external stakeholders])                                                                                                              AS [Change - Number of external stakeholders],
    COALESCE(a.[Change - Number of internal stakeholders],
             b.[Change - Number of internal stakeholders],
             c.[Change - Number of internal stakeholders])                                                                                                              AS [Change - Number of internal stakeholders],
    COALESCE(a.[Change - Significance Magnitude],
             b.[Change - Significance (Magnitude)],
             c.[Change - Significance (Magnitude)])                                                                                                                     AS [Change - Significance Magnitude],
    COALESCE(a.[Change - Willingness],              b.[Change - Willingness],                       c.[Change - Willingness])                                           AS [Change - Willingness],
    COALESCE(a.[Impact on any laws or regulation compliance],
             b.[Impact on any laws or regulation compliance],
             c.[Impact on any laws or regulation compliance])                                                                                                           AS [Impact on any laws or regulation compliance],
    COALESCE(a.[What law or regulation is impacted?],
             b.[What law or regulation is impacted?],
             c.[What law or regulation is impacted?])                                                                                                                   AS [What law or regulation is impacted?],
    COALESCE(a.[PPM Project Number],                b.[PPM Project Number],                         c.[PPM Project Number])                                             AS [PPM Project Number],
    COALESCE(a.[Is there a manual solution?],       b.[Is there a manual solution?],                c.[Is there a manual solution?])                                    AS [Is there a manual solution?],
    COALESCE(a.[If there is a manual solution_ explain_],
             b.[If there is a manual solution, explain:],
             c.[If there is a manual solution, explain:])                                                                                                               AS [If there is a manual solution_ explain_],
    COALESCE(a.[L2 Net Recurring Benefits $_ annualized-P&L_Hard],
             b.[L2 Net Recurring Benefits ($, annualized)-P&L/Hard],
             c.[L2 Net Recurring Benefits ($, annualized)-P&L/Hard])                                                                                                   AS [L2 Net Recurring Benefits $_ annualized-P&L_Hard],
    COALESCE(a.[L2 Net Recurring Benefits $_ annualized-Soft],
             b.[L2 Net Recurring Benefits ($, annualized)-Soft],
             c.[L2 Net Recurring Benefits ($, annualized)-Soft])                                                                                                        AS [L2 Net Recurring Benefits $_ annualized-Soft],
    COALESCE(a.[L2 One-time Benefit $-Soft],
             b.[L2 One-time Benefit ($)-Soft],
             c.[L2 One-time Benefit ($)-Soft])                                                                                                                         AS [L2 One-time Benefit ($)-Soft],
    COALESCE(a.[L3 Net Recurring Benefits $_ annualized-P&L_Hard],
             b.[L3 Net Recurring Benefits ($, annualized)-P&L/Hard],
             c.[L3 Net Recurring Benefits ($, annualized)-P&L/Hard])                                                                                                   AS [L3 Net Recurring Benefits $_ annualized-P&L_Hard],
    COALESCE(a.[L4 Net Recurring Benefits $_ annualized-P&L_Hard],
             b.[L4 Net Recurring Benefits ($, annualized)-P&L/Hard],
             c.[L4 Net Recurring Benefits ($, annualized)-P&L/Hard])                                                                                                   AS [L4 Net Recurring Benefits $_ annualized-P&L_Hard],
    COALESCE(a.[EAI #],                             b.[EAI #],                                      c.[EAI #])                                                          AS [EAI #],
    COALESCE(a.[Azure Subscription Group],          b.[Azure Subscription Group],                   c.[Azure Subscription Group])                                       AS [Azure Subscription Group],
    COALESCE(a.[MS Azure Usage Size],               b.[MS Azure Usage Size],                        c.[MS Azure Usage Size])                                            AS [MS Azure Usage Size],
    COALESCE(a.[Service_ terms_ P&D_ transits_ etc.],
             b.[Service, terms, P&D, transits, etc.],
             c.[Service, terms, P&D, transits, etc.])                                                                                                                   AS [Service_ terms_ P&D_ transits_ etc.],
    COALESCE(a.[Pricing and Surcharges],            b.[Pricing and Surcharges],                     c.[Pricing and Surcharges])                                         AS [Pricing and Surcharges],
    COALESCE(a.[Customer's external experience],    b.[Customer's external experience],              c.[Customer's external experience])                                 AS [Customer's external experience],
    COALESCE(a.[Portfolio and Products],            b.[Portfolio and Products],                     c.[Portfolio and Products])                                         AS [Portfolio and Products],
    COALESCE(a.[Communication Plans G2M and G2S],
             b.[Communication Plans (G2M and G2S)],
             c.[Communication Plans (G2M and G2S)])                                                                                                                     AS [Communication Plans G2M and G2S],
    COALESCE(a.[CCH Greenlight],                    b.[CCH Greenlight],                             c.[CCH Greenlight])                                                 AS [CCH Greenlight],
    COALESCE(a.[Commercial Portfolio Greenlight],   b.[Commercial Portfolio Greenlight],            c.[Commercial Portfolio Greenlight])                                AS [Commercial Portfolio Greenlight],
    COALESCE(a.[Data & AI Portfolio Greenlight],    b.[Data & AI Portfolio Greenlight],             c.[Data & AI Portfolio Greenlight])                                 AS [Data & AI Portfolio Greenlight],
    COALESCE(a.[Enterprise Services Portfolio Greenlight],
             b.[Enterprise Services Portfolio Greenlight],
             c.[Enterprise Services Portfolio Greenlight])                                                                                                              AS [Enterprise Services Portfolio Greenlight],
    COALESCE(a.[Platform Portfolio Greenlight],     b.[Platform Portfolio Greenlight],              c.[Platform Portfolio Greenlight])                                  AS [Platform Portfolio Greenlight],
    COALESCE(a.[Supply Chain Operations Portfolio Greenlight],
             b.[Supply Chain Operations Portfolio Greenlight],
             c.[Supply Chain Operations Portfolio Greenlight])                                                                                                          AS [Supply Chain Operations Portfolio Greenlight],
    COALESCE(a.[Commercial PEO],                    b.[Commercial PEO],                             c.[Commercial PEO])                                                 AS [Commercial PEO],
    COALESCE(a.[Data & AI PEO],                     b.[Data & AI PEO],                              c.[Data & AI PEO])                                                  AS [Data & AI PEO],
    COALESCE(a.[Enterprise Services PEO],           b.[Enterprise Services PEO],                    c.[Enterprise Services PEO])                                        AS [Enterprise Services PEO],
    COALESCE(a.[Platform PEO],                      b.[Platform PEO],                               c.[Platform PEO])                                                   AS [Platform PEO],
    COALESCE(a.[Supply Chain Operations PEO],       b.[Supply Chain Operations PEO],                c.[Supply Chain Operations PEO])                                    AS [Supply Chain Operations PEO],
    COALESCE(a.[CCH Lead],                          b.[CCH Lead],                                   c.[CCH Lead])                                                       AS [CCH Lead],
    COALESCE(a.[Epic Owner],                        b.[Epic Owner],                                 c.[Epic Owner])                                                     AS [Epic Owner],
    COALESCE(a.[Finance Domain Lead],               b.[Finance Domain Lead],                        c.[Finance Domain Lead])                                            AS [Finance Domain Lead],
    COALESCE(a.[Time to Value],                     b.[Time to Value],                              c.[Time to Value])                                                  AS [Time to Value],
    COALESCE(a.[Money Step MS Date],                b.[Money Step MS Date],                         c.[Money Step MS Date])                                             AS [Money Step MS Date],
    COALESCE(a.[What is the time criticality?],     b.[What is the time criticality?],              c.[What is the time criticality?])                                  AS [What is the time criticality?],
    COALESCE(a.[CCH Notes],                         b.[CCH Notes],                                  c.[CCH Notes])                                                      AS [CCH Notes],
    COALESCE(a.[Commercial Portfolio Greenlight Notes],
             b.[Commercial Portfolio Greenlight Notes],
             c.[Commercial Portfolio Greenlight Notes])                                                                                                                 AS [Commercial Portfolio Greenlight Notes],
    COALESCE(a.[Data & AI Portfolio Greenlight Notes],
             b.[Data & AI Portfolio Greenlight Notes],
             c.[Data & AI Portfolio Greenlight Notes])                                                                                                                  AS [Data & AI Portfolio Greenlight Notes],
    COALESCE(a.[Enterprise Services Portfolio Greenlight Notes],
             b.[Enterprise Services Portfolio Greenlight Notes],
             c.[Enterprise Services Portfolio Greenlight Notes])                                                                                                        AS [Enterprise Services Portfolio Greenlight Notes],
    COALESCE(a.[Platform Portfolio Greenlight Notes],
             b.[Platform Portfolio Greenlight Notes],
             c.[Platform Portfolio Greenlight Notes])                                                                                                                   AS [Platform Portfolio Greenlight Notes],
    COALESCE(a.[Supply Chain Operations Portfolio Greenlight Notes],
             b.[Supply Chain Operations Portfolio Greenlight Notes],
             c.[Supply Chain Operations Portfolio Greenlight Notes])                                                                                                    AS [Supply Chain Operations Portfolio Greenlight Notes],
    COALESCE(a.[Notes on SL1 Decision],             b.[Notes on SL1 Decision],                      c.[Notes on SL1 Decision])                                          AS [Notes on SL1 Decision],
    COALESCE(a.[SL2 Domain Lead Notes],             b.[SL2 Domain Lead Notes],                      c.[SL2 Domain Lead Notes])                                          AS [SL2 Domain Lead Notes],
    COALESCE(a.[SL2 EPM Notes],                     b.[SL2 EPM Notes],                              c.[SL2 EPM Notes])                                                  AS [SL2 EPM Notes],
    COALESCE(a.[SL2 Finance Domain Lead Notes],     b.[SL2 Finance Domain Lead Notes],              c.[SL2 Finance Domain Lead Notes])                                  AS [SL2 Finance Domain Lead Notes],
    COALESCE(a.[SL3 Domain Lead Notes],             b.[SL3 Domain Lead Notes],                      c.[SL3 Domain Lead Notes])                                          AS [SL3 Domain Lead Notes],
    COALESCE(a.[SL3 EPM Notes],                     b.[SL3 EPM Notes],                              c.[SL3 EPM Notes])                                                  AS [SL3 EPM Notes],
    COALESCE(a.[SL3 Finance Domain Lead Notes],     b.[SL3 Finance Domain Lead Notes],              c.[SL3 Finance Domain Lead Notes])                                  AS [SL3 Finance Domain Lead Notes],
    COALESCE(a.[SL3 SVP Finance Notes],             b.[SL3 SVP Finance Notes],                      c.[SL3 SVP Finance Notes])                                          AS [SL3 SVP Finance Notes],
    COALESCE(a.[SL3 TO Finance Notes],              b.[SL3 TO Finance Notes],                       c.[SL3 TO Finance Notes])                                           AS [SL3 TO Finance Notes],
    COALESCE(a.[SL4 Domain Lead Notes],             b.[SL4 Domain Lead Notes],                      c.[SL4 Domain Lead Notes])                                          AS [SL4 Domain Lead Notes],
    COALESCE(a.[SL4 Finance Domain Lead Notes],     b.[SL4 Finance Domain Lead Notes],              c.[SL4 Finance Domain Lead Notes])                                  AS [SL4 Finance Domain Lead Notes],
    COALESCE(a.[SL5 Finance Domain Lead Notes],     b.[SL5 Finance Domain Lead Notes],              c.[SL5 Finance Domain Lead Notes])                                  AS [SL5 Finance Domain Lead Notes],
    COALESCE(a.[SL5 TO Finance Notes],              b.[SL5 TO Finance Notes],                       c.[SL5 TO Finance Notes])                                           AS [SL5 TO Finance Notes],
    COALESCE(a.[EPM],                               b.[EPM],                                        c.[EPM])                                                            AS [EPM],
    COALESCE(a.[If 'Yes'_ note the laws or regulatory bodies_],
             b.[If 'Yes', note the laws or regulatory bodies:],
             c.[If 'Yes', note the laws or regulatory bodies:])                                                                                                         AS [If 'Yes', note the laws or regulatory bodies:],
    COALESCE(a.[AgilePlace Board],                  b.[AgilePlace Board],                           c.[AgilePlace Board])                                               AS [AgilePlace Board],
    COALESCE(a.[Does this require technology?],     b.[Does this require technology?],              c.[Does this require technology?])                                  AS [Does this require technology?],
    COALESCE(a.[Investment Dependencies],           b.[Investment Dependencies],                    c.[Investment Dependencies])                                        AS [Investment Dependencies],
    COALESCE(a.[Submitted to Triage],               b.[Submitted to Triage],                        c.[Submitted to Triage])                                            AS [Submitted to Triage],


    /* ==========================================
       SECTION 2: [PlanviewMigration_Output].[Initiatives_v8] ADDITIONAL COLUMNS (117-123)
       Alias: b  |  COALESCE(b, c) since SP3 also has these columns
       ========================================== */

    COALESCE(b.[Flow Type - Step 1],                        c.[Flow Type - Step 1])                 AS [Flow Type - Step 1],
    COALESCE(b.[Estimated Annualized Value Range_Step 1],   c.[Estimated Annualized Value Range_Step 1])    AS [Estimated Annualized Value Range_Step 1],
    COALESCE(b.[Estimated Annualized Value Range_Step 2],   c.[Estimated Annualized Value Range_Step 2])    AS [Estimated Annualized Value Range_Step 2],
    COALESCE(b.[Estimated Annualized Value Range_Step 3],   c.[Estimated Annualized Value Range_Step 3])    AS [Estimated Annualized Value Range_Step 3],
    COALESCE(b.[Estimated Value Range_Consolidated],        c.[Estimated Value Range_Consolidated])         AS [Estimated Value Range_Consolidated],
    COALESCE(b.[Flow Type],                                 c.[Flow Type])                          AS [Flow Type],
    COALESCE(b.[Stage],                                     c.[Stage])                              AS [Stage],


    /* ==========================================
       SECTION 3: [PlanviewMigration_Transform_Output].[Initiatives_SP3_v1] ADDITIONAL COLUMNS
       Alias: c  |  SP3-only columns (Status excluded)
       ========================================== */

    c.[Strategy Type]                                       AS [Strategy Type],
    c.[Disposition]                                         AS [Disposition],
    c.[SL3 EPG Approval]                                    AS [SL3 EPG Approval],
    c.[SL3 Business Finance Approval]                       AS [SL3 Business Finance Approval],
    c.[Ready for L3 EPM Quality Check?]                     AS [Ready for L3 EPM Quality Check?],
    c.[L3 EPM Review 1]                                     AS [L3 EPM Review 1],
    c.[Ready for L3 Epic Approval?]                         AS [Ready for L3 Epic Approval?],
    c.[L3 Epic Approval]                                    AS [L3 Epic Approval],
    c.[SL3 Program Owner Approval]                          AS [SL3 Program Owner Approval],
    c.[SL3 D&T Captain Approval]                            AS [SL3 D&T Captain Approval],
    c.[SL3 ESPM Review]                                     AS [SL3 ESPM Review],
    c.[SL3 TO Approval]                                     AS [SL3 TO Approval],
    c.[SL3 D&T Finance Approval]                            AS [SL3 D&T Finance Approval],
    c.[SL3 DTU Approval]                                    AS [SL3 DTU Approval],
    c.[SL3 D&T SMO Review]                                  AS [SL3 D&T SMO Review],
    c.[L3 ESPM Review]                                      AS [L3 ESPM Review],
    c.[L3 D&T SMO Review]                                   AS [L3 D&T SMO Review],
    c.[SL4 Close Work Bundle -D&T Finance Approval]         AS [SL4 Close Work Bundle -D&T Finance Approval],
    c.[Work Status]                                         AS [Work Status],
    c.[Other Impacted Portfolios]                           AS [Other Impacted Portfolios],
    c.[Demand Type - Legacy]                                AS [Demand Type - Legacy],
    c.[Execution Type - Legacy]                             AS [Execution Type - Legacy],
    c.[Execution Type]                                      AS [Execution Type],
    c.[Parent Sequence ID]                                  AS [Parent Sequence ID],


    /* ==========================================
       SECTION 4: SOURCE TRACEABILITY FLAGS
       ========================================== */

    CASE WHEN a.[Strategy Seq ID] IS NOT NULL THEN 'Y' ELSE 'N' END    AS [In_Initiatives_v12],
    CASE WHEN b.[Strategy Seq ID] IS NOT NULL THEN 'Y' ELSE 'N' END    AS [In_Initiatives_v8],
    CASE WHEN c.[Strategy Seq ID] IS NOT NULL THEN 'Y' ELSE 'N' END    AS [In_Initiatives_SP3_v1]

FROM      [PlanviewMigration_Output].[Initiatives_v12]                          a
FULL OUTER JOIN [PlanviewMigration_Output].[Initiatives_v8]                     b   ON  a.[Strategy Seq ID] = b.[Strategy Seq ID]
FULL OUTER JOIN [PlanviewMigration_Transform_Output].[Initiatives_SP3_v1]       c   ON  COALESCE(a.[Strategy Seq ID], b.[Strategy Seq ID]) = c.[Strategy Seq ID];
